# Generated by Django 5.2 on 2025-05-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('jefe_brigada', 'Jefe de Brigada'), ('tecnico', 'Técnico'), ('botanico', 'Botánico')], max_length=20),
        ),
    ]
